templates:
  install-googet:
    GooGetInstall: [['googet', ['https://your-internal-repository.com/branch-%']]]

  common:
    GooGetInstall: [
      ['7zip'],
      ['powershell'],
    ]

  client:
    GooGetInstall: [
      ['chrome'],
      ['chromeremotedesktophost'],
    ]

  gce_server:
    GooGetInstall: [
      ['osquery-cloud'],
    ]

controls:
- pin:
    'os_code': ['win2012r2', 'win2016', 'win2019']
    'computer_model': ['!Google Compute Engine']
  template:
  - install-googet
  - common

- pin:
    'os_code': ['win10']
    'computer_model': ['!Google Compute Engine']
  template:
  - install-googet
  - common
  - client

- pin:
    'os_code': ['win10']
    'computer_model': ['Google Compute Engine']
  template:
  - common
  - client

- pin:
    'os_code': ['win2012r2', 'win2016', 'win2019']
    'computer_model': ['Google Compute Engine']
  template:
  - common
  - gce_server
